update substrate and frontier

diff --git a/vendors/polkadot-sdk/.github/workflows/tests-misc.yml b/vendors/polkadot-sdk/.github/workflows/tests-misc.yml
--- a/vendors/polkadot-sdk/.github/workflows/tests-misc.yml
+++ b/vendors/polkadot-sdk/.github/workflows/tests-misc.yml
@@ -3,7 +3,7 @@ name: tests misc
 on:
   push:
     branches:
-      - master
+      - stable2506
   pull_request:
     types: [opened, synchronize, reopened, ready_for_review]
   merge_group:
@@ -14,7 +14,10 @@ concurrency:
 # Jobs in this workflow depend on each other, only for limiting peak amount of spawned workers
 
 jobs:
+  isdraft:
+    uses: ./.github/workflows/reusable-isdraft.yml
   preflight:
+    needs: isdraft
     uses: ./.github/workflows/reusable-preflight.yml
 
   # more information about this job can be found here:
@@ -61,9 +64,9 @@ jobs:
       - name: script
         run: |
           cd substrate/frame/examples/offchain-worker/
-          forklift cargo build --locked --target=wasm32-unknown-unknown --no-default-features
+          RUSTFLAGS="--cfg substrate_runtime" forklift cargo build --locked --target=wasm32-unknown-unknown --no-default-features
           cd ../basic
-          forklift cargo build --locked --target=wasm32-unknown-unknown --no-default-features
+          RUSTFLAGS="--cfg substrate_runtime" forklift cargo build --locked --target=wasm32-unknown-unknown --no-default-features
 
   test-frame-ui:
     timeout-minutes: 60
@@ -124,7 +127,7 @@ jobs:
     timeout-minutes: 60
     strategy:
       matrix:
-        branch: [master, current]
+        branch: [stable2506, current]
     runs-on: ${{ needs.preflight.outputs.RUNNER }}
     container:
       image: ${{ needs.preflight.outputs.IMAGE }}
@@ -132,9 +135,9 @@ jobs:
       - name: Checkout
         uses: actions/checkout@v4
         with:
-          # if branch is master, use the branch, otherwise set empty string, so it uses the current context
+          # if branch is stable2506, use the branch, otherwise set empty string, so it uses the current context
           # either PR (including forks) or merge group (main repo)
-          ref: ${{ matrix.branch == 'master' && matrix.branch || '' }}
+          ref: ${{ matrix.branch == 'stable2506' && matrix.branch || '' }}
 
       - name: script
         run: |
@@ -163,14 +166,16 @@ jobs:
       - name: Checkout
         uses: actions/checkout@v4
 
-      - name: Download artifact (master run)
+      - name: Download artifact (stable2506 run)
         uses: actions/download-artifact@v4.1.8
+        continue-on-error: true
         with:
-          name: cargo-check-benches-master-${{ github.sha }}
-          path: ./artifacts/master
+          name: cargo-check-benches-stable2506-${{ github.sha }}
+          path: ./artifacts/stable2506
 
       - name: Download artifact (current run)
         uses: actions/download-artifact@v4.1.8
+        continue-on-error: true
         with:
           name: cargo-check-benches-current-${{ github.sha }}
           path: ./artifacts/current
@@ -178,16 +183,22 @@ jobs:
       - name: script
         id: compare
         run: |
-          if [ "${{ github.ref_name }}" = "master" ]; then
-            echo -e "Exiting on master branch"
+          if [ "${{ github.ref_name }}" = "stable2506" ]; then
+            echo -e "Exiting on stabel branch"
             exit 0
           fi
 
+          # fail if no artifacts
+          if [ ! -d ./artifacts/stable2506 ] || [ ! -d ./artifacts/current ]; then
+            echo "No artifacts found"
+            exit 1
+          fi
+
           docker run --rm \
-          -v $PWD/artifacts/master:/artifacts/master \
+          -v $PWD/artifacts/stable2506:/artifacts/stable2506 \
           -v $PWD/artifacts/current:/artifacts/current \
           paritytech/node-bench-regression-guard:latest \
-          node-bench-regression-guard --reference /artifacts/master --compare-with /artifacts/current
+          node-bench-regression-guard --reference /artifacts/stable2506 --compare-with /artifacts/current
 
           if [ $? -ne 0 ]; then
             FAILED_MSG='### node-bench-regression-guard failed ❌, check the regression in *cargo-check-benches* job'
@@ -347,23 +358,49 @@ jobs:
           echo "RUST_VERSION=${RUST_VERSION}" >> $GITHUB_ENV
       - name: Set up Homebrew
         uses: Homebrew/actions/setup-homebrew@1ccc07ccd54b6048295516a3eb89b192c35057dc # master from 12.09.2024
+      # Is broken because of different bash versions
+      # - name: Install rust ${{ env.RUST_VERSION }}
+      #   uses: actions-rust-lang/setup-rust-toolchain@1780873c7b576612439a134613cc4cc74ce5538c # v1.15.2
+      #   with:
+      #     cache: false
+      #     toolchain: ${{ env.RUST_VERSION }}
+      #     target: wasm32-unknown-unknown
+      #     components: cargo, clippy, rust-docs, rust-src, rustfmt, rustc, rust-std
       - name: Install rust ${{ env.RUST_VERSION }}
-        uses: actions-rust-lang/setup-rust-toolchain@11df97af8e8102fd60b60a77dfbf58d40cd843b8 # v1.10.1
-        with:
-          cache: false
-          toolchain: ${{ env.RUST_VERSION }}
-          target: wasm32-unknown-unknown
-          components: cargo, clippy, rust-docs, rust-src, rustfmt, rustc, rust-std
+        run: |
+          curl https://sh.rustup.rs -sSf | sh -s -- -y --default-toolchain $RUST_VERSION
+          source $HOME/.cargo/env
+          rustup target add wasm32-unknown-unknown
+          rustup component add clippy rust-docs rust-src rustfmt rustc rust-std
       - name: Install protobuf
         run: brew install protobuf
+      - name: install solc
+        run: brew install solidity
+      - name: Install resolc
+        run: |
+          source $HOME/.cargo/env
+          VERSION="0.3.0"
+          ASSET_URL="https://github.com/paritytech/revive/releases/download/v$VERSION/resolc-universal-apple-darwin"
+          echo "Downloading resolc v$VERSION from $ASSET_URL"
+          curl -Lsf --show-error -o $HOME/.cargo/bin/resolc "$ASSET_URL"
+          chmod +x $HOME/.cargo/bin/resolc
+          xattr -c $HOME/.cargo/bin/resolc
+          resolc --version
+      - name: Install llvm
+        run: |
+          brew install llvm@20
+          brew link llvm@20
       - name: cargo info
         run: |
+          source $HOME/.cargo/env
           echo "######## rustup show ########"
           rustup show
           echo "######## cargo --version ########"
           cargo --version
       - name: Run cargo check
-        run: cargo check --workspace --locked
+        run: |
+          source $HOME/.cargo/env
+          cargo check --workspace --locked
 
   confirm-required-test-misc-jobs-passed:
     runs-on: ubuntu-latest
@@ -379,7 +416,6 @@ jobs:
       - check-tracing
       - cargo-check-each-crate
       - test-deterministic-wasm
-      - cargo-check-all-crate-macos
       # - cargo-hfuzz remove from required for now, as it's flaky
     if: always() && !cancelled()
     steps:
